### ISSUE TITLE
Setting for the point effect size

### ISSUE THREAD

**Issue by alunats** [KhanKawsar/EstimationPlot#1]
Thank you for your work on this wonderful tool that is Durga.
I have a question about the possibility of setting the effect size for the point size. As the 'cex' parameter changes, both the size of the fonts on the axes and the point size change.
'ef.size.params = list(las = 1, cex = 1, mgp = c(2.5, 1, 0))'

I tried that, but no change.
par(cex.axis=0.5,cex.lab=0.5,cex=0.5)

Is it possible to selectively resize only a point?

**Comment by JimMcL** [comment]
`DurgaPlot` now has a parameter `ef.size.cex` that provides control over the size of the effect size mean symbol. It is available in the development version of Durga (for now). See the [README](https://github.com/KhanKawsar/EstimationPlot) for installation instructions
